config/routes.rb
Rails.application.routes.draw do
  root "flats#index"
  resources :flats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:new, :create, :show]
  
  def index
    @flats = Flat.all
  end

  def show
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div class="p-0 m-2 card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body bg-light">
    <h5 class="card-title"><%= flat.name %></h5>
    <p class="card-text"><%= flat.description %></p>
  </div>
  <div class="card-body">
    <%= link_to "More info", flat_path(flat), class: "card-link" %>
    <%= link_to "Edit", edit_flat_path(flat), class: "card-link text-warning" %>
    <%= link_to "Delete", flat_path(flat), class: "card-link text-danger" %>
    <%# <a href="#" class="card-link text-warning">Edit</a>
    <a href="#" class="card-link text-danger">Remove</a> %>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <% @flats.each do |flat| %>
      <%= render "flat", flat: flat %>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map bg-light">

</div>

<div class="container margin-top-negative">
  <div class="card border mb-3" style="max-width: 65%;">
    <div class="card-body">
      <h5 class="card-title"><%= @flat.name %></h5>
      <p class="card-text"><%= @flat.address %></p>
    </div>
  </div>
</div>

<div class="container margin-top-negative">
  <div class="card border mb-3" style="max-width: 65%;">
    <div class="card-body">
      <h5 class="card-title">A bit more about this flat..</h5>
      <p class="card-text"><%= @flat.description %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= render "/shared/navbar" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Simple Airbnb</a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <a class="btn btn-outline-success" href="/flats/new">Add Flat</a>
  </div>
</nav>